apiVersion: v1
kind: ConfigMap
metadata:
  name: library-mongo-config
data:
  mongodb.conf: |
    net:
      bindIp: 0.0.0.0
      port: 27017
    {{- if .Values.mongo.enableReplicaSet }}
    replication:
      replSetName: rs0
    {{- end }}